image: mysql:5.6.40 # your image

pipelines:
  branches:
    develop:
      - step:
          caches:
            - pip
          script:
            # Mysql
            - service mysql start
            - mysql < /ec.sql
            - mysql < /common.sql
            - mysql < /user_glowmee.sql
            - mysql < /privilege.sql


            # Python packages
            - pip3 install -r requirements.txt


            # PEP8
            - flake8 .


            # TDD
            - cp /common.ini $BITBUCKET_CLONE_DIR/settings/configs
            - python3 $BITBUCKET_CLONE_DIR/manage.py test test
